=== chc-dev/schema/schema/chief/chief-quantity-sample-1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://chc-datapoint.mybluemix.net/schema/chief/chief-quantity-sample-1.0.json",
    "description": "A quantity sample that represents data using a single numerical value.",
    "type": "object",
    "references": [
        {
            "description": "The class reference for Apple HealthKit HKQuantitySample.",
            "url": "https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HKQuantitySample_Class/index.html"
        }
    ],
    "properties": {
        "effective_time_frame": {
            "description": "The time frame when this sample occurred. When the HKSample `startDate` and `endDate` values are different, we recommend using the `time_interval` time frame property, and when they are the same, we recommend using the `date_time` time frame property.",
            "$ref": "time-frame-1.0.json"
        },
        "quantity_type": {
            "description": "The quantity type for this sample.",
            "anyOf": [
                {
                    "$ref": "hk-quantity-type-1.0.json"
                },
                {
                    "$ref": "chief-quantity-type-1.0.json"
                }
            ]
        },
        "quantity": {
            "description": "The quantity of this sample, as a unit and value.",
            "$ref": "quantity-1.0.json"
        },
        "metadata": {
            "description": "An array of extra information describing this sample.",
            "type": "object",
            "allOf": [
                {
                    "$ref": "chief-metadata-item-1.0.json"
                },
                {
                    "$ref": "hk-metadata-item-1.0.json"
                }
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "quantity_type",
        "quantity"
    ]
}

=== chc-dev/schema/test-data/chief/step-count/1.0/shouldPass/step-count.json
{
    "quantity": {
        "value": 78
    },
    "quantity_type": "stepCount",
    "effective_time_frame": {
        "time_interval": {
            "start_date_time": "2018-04-05T00:00:00Z",
            "end_date_time": "2018-04-06T00:00:00Z"
        }
    },
    "metadata": {
        "src_vendor": "GOLiFE",
        "modality": "sensed"
    }
}
